# Generated by Django 5.1.4 on 2025-05-25 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0002_post"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Post",
            new_name="Pst",
        ),
    ]
