# Generated by Django 5.1.4 on 2025-05-25 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0003_rename_post_pst"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Pst",
            new_name="Post",
        ),
    ]
